#!/usr/bin/env python3
"""Make resemble-perth 1.0.1 independent of ``pkg_resources``.

Why this exists
---------------
``resemble-perth`` 1.0.1 (a hard dependency of ``chatterbox-tts``) starts
``perth/perth_net/__init__.py`` with::

    from pkg_resources import resource_filename
    PREPACKAGED_MODELS_DIR = resource_filename(__name__, "pretrained")

**setuptools 82 removed ``pkg_resources``** (pypa/setuptools#5174, Feb 2026), so
that first line raises ``ImportError``. ``perth/__init__.py`` catches it with a
bare ``except ImportError`` and quietly sets
``PerthImplicitWatermarker = None``. Chatterbox then dies inside
``ChatterboxMultilingualTTS.__init__`` on ``perth.PerthImplicitWatermarker()``
with the very unhelpful message::

    TypeError: 'NoneType' object is not callable

That is exactly the failure of RunPod job ``2b6fb1ee-…-e1`` (image
``sha-7490e34``, delayTime 211.7 s, executionTime 20.4 s): the worker had
already downloaded and loaded the 3 GB checkpoints and only broke while
constructing the model wrapper.

What it does
------------
Rewrites that import into a stdlib-only ``resource_filename`` shim
(``importlib.util.find_spec`` + ``os.path``) that returns the same filesystem
path the original did. The installed package is a plain directory, so resolving
the path through the loader is exact.

Idempotent: a tree that no longer mentions ``pkg_resources`` is left alone, and
any *other* ``pkg_resources`` use inside the package makes the run fail loudly
(fail-closed) instead of shipping a half-patched image.

    python3 patch_perth.py --verify        # inside the image: patch + import check
    python3 patch_perth.py                 # patch only (offline CI test runner)
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import sys
from pathlib import Path

MARKER = "generated by tts-worker/patch_perth.py"

OLD_IMPORT = "from pkg_resources import resource_filename\n"

NEW_BLOCK = '''# resource_filename shim %s: resemble-perth 1.0.1 used pkg_resources,
# which setuptools>=82 removed; perth/__init__.py turns the ImportError into a
# silent `PerthImplicitWatermarker = None` and chatterbox then dies with
# "'NoneType' object is not callable".
import importlib.util as _importlib_util
import os as _os


def resource_filename(pkg, resource):
    """Return the on-disk path of ``resource`` inside package ``pkg``.

    Equivalent to the pkg_resources helper for a normally installed package,
    using only the standard library.
    """
    spec = _importlib_util.find_spec(pkg)
    if spec is None:
        raise ImportError("no package named %%r" %% (pkg,))
    locations = list(getattr(spec, "submodule_search_locations", None) or [])
    if locations:
        base = locations[0]
    else:
        origin = getattr(spec, "origin", None)
        if not origin:
            raise ImportError("cannot locate package %%r" %% (pkg,))
        base = _os.path.dirname(origin)
    return _os.path.join(base, resource)
''' % MARKER


def patch_file(path: Path) -> str:
    """Patch one ``__init__.py``. Returns 'patched', 'clean' or 'leftover'."""
    text = path.read_text(encoding="utf-8")
    if MARKER in text:
        return "clean"
    if OLD_IMPORT not in text:
        # Nothing to replace here; report whether anything else needs attention.
        return "leftover" if "pkg_resources" in text else "clean"
    path.write_text(text.replace(OLD_IMPORT, NEW_BLOCK, 1), encoding="utf-8")
    return "patched"


def perth_roots() -> list[Path]:
    """Every installed directory of the ``perth`` package."""
    roots = []
    try:
        spec = importlib.util.find_spec("perth")
    except Exception:  # noqa: BLE001  (a broken install raises here)
        spec = None
    if spec is not None:
        for loc in list(getattr(spec, "submodule_search_locations", None) or []):
            roots.append(Path(loc))
    if not roots:
        # find_spec imports parent packages only, so this stays cheap; fall back
        # to a plain site-packages scan if perth is importable but has no path.
        for entry in sys.path:
            candidate = Path(entry) / "perth"
            if candidate.is_dir():
                roots.append(candidate)
    return roots


def main(argv=None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true",
                        help="import perth afterwards and assert the watermarker exists")
    parser.add_argument("--root", action="append", default=None,
                        help="patch this perth directory instead of the installed one")
    args = parser.parse_args(argv)

    roots = [Path(r) for r in args.root] if args.root else perth_roots()
    if not roots:
        print("FATAL: the perth package is not installed", file=sys.stderr)
        return 1

    targets = []
    for root in roots:
        targets.extend(sorted(root.rglob("*.py")))
    if not targets:
        print(f"FATAL: no python files under {roots}", file=sys.stderr)
        return 1

    results = {}
    for path in targets:
        results[str(path)] = patch_file(path)

    for path, result in results.items():
        print(f"{result:8s} {path}")

    leftovers = [p for p, r in results.items() if r == "leftover"]
    if leftovers:
        print("FATAL: pkg_resources is still referenced by: " + ", ".join(leftovers),
              file=sys.stderr)
        return 2

    if args.verify:
        import perth  # noqa: PLC0415  (must run after the patch)
        if perth.PerthImplicitWatermarker is None:
            print("FATAL: perth.PerthImplicitWatermarker is still None", file=sys.stderr)
            return 3
        print("perth.PerthImplicitWatermarker:", perth.PerthImplicitWatermarker)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
